channels:
  - name: "Ansh Lamba"
    handle: "@AnshLambaJSR"
    channel_id: "UCu7lQE-L5gzt8aD7zuuufjw"
    uploads_playlist_id: "UUu7lQE-L5gzt8aD7zuuufjw"

  - name: "Ankit Bansal"
    handle: "@ankitbansal6"
    channel_id: "UCk7NcgnqCmui1AV7MTXZwOw"
    uploads_playlist_id: "UUk7NcgnqCmui1AV7MTXZwOw"

  - name: "techTFQ"
    handle: "@techTFQ"
    channel_id: "UCnz-ZXXER4jOvuED5trXfEA"
    uploads_playlist_id: "UUnz-ZXXER4jOvuED5trXfEA"